version: '3.9'

services:
  db_web:
    image: 'modtree/postgres:0.5.0'
    profiles: ['all', 'db']
    ports:
      - '4000:5432'
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: web
  db_test:
    image: 'modtree/postgres:0.5.0'
    profiles: ['all', 'db']
    ports:
      - '4001:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
  server:
    image: 'modtree/server:0.5.8'
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile.server
    profiles: ['all', 'server']
    depends_on:
      - 'db_web'
    ports:
      - '8080:8080'
    environment:
      DATABASE_TYPE: POSTGRES
      POSTGRES_DATABASE: web
      POSTGRES_USERNAME: web
      POSTGRES_PASSWORD: web
      POSTGRES_HOST: db_web
      POSTGRES_PORT: 5432
