name: database lint

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  push:
    branches:
      - ci-tele
      - dev
      - k
      - w

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: ğŸ” Check out repository code
        uses: actions/checkout@v3

      - name: ğŸ§¶ Install yarn
        run: yarn
      
      - name: ğŸ“¦ build & lint database functions
        run: yarn build:db
