on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - dev
      - ci-test
      - k
      - w

jobs:
  build everything:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ” Check out repository code
        uses: actions/checkout@v3

      - name: ğŸ§¶ Install yarn
        run: yarn

      - name: ğŸ”¥ Firelink packages for backend/functions
        working-directory: ./apps/backend/functions
        run: yarn link:deps

      - name: ğŸ“¦ Project-wide build & lint
        run: yarn build
