on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  push:
    branches:
      - ci-test
      - dev
      - k
      - w

jobs:
  lint-database:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ” Check out repository code
        uses: actions/checkout@v3

      - name: ğŸ§¶ Install yarn
        run: yarn

      - name: ğŸ“¦ build & lint database functions
        run: yarn build:db
